 MODULE setup

 IMPLICIT NONE

 INTEGER, PARAMETER :: DP = SELECTED_REAL_KIND(p=16) 

 LOGICAL :: VISMODE, IS_DEFORMING, IS_RESTART


 REAL(KIND=DP), PARAMETER :: gam = 1.40_DP, &
							 pi = ACOS(-1.0_DP)

 REAL(KIND=DP), ALLOCATABLE, DIMENSION (:) :: Xs, Xf
 REAL(KIND=DP), ALLOCATABLE, DIMENSION (:,:) :: Lmat, Mmat
 REAL(KIND=DP), ALLOCATABLE, DIMENSION (:,:,:) :: Jac
 REAL(KIND=DP), ALLOCATABLE, DIMENSION (:,:,:,:) :: XXSolu
 REAL(KIND=DP), ALLOCATABLE, DIMENSION (:,:,:,:) :: dpdxs, dpdxf1, dpdxf2
 REAL(KIND=DP), ALLOCATABLE, DIMENSION (:,:,:,:) :: Q, resid
 REAL(KIND=DP), ALLOCATABLE, DIMENSION (:,:,:,:) :: RK_k1, RK_k2, RK_k3, RK_k4, RK_k5
 REAL(KIND=DP), ALLOCATABLE, DIMENSION (:,:,:,:) :: F1, G2
 REAL(KIND=DP), ALLOCATABLE, DIMENSION (:,:,:,:,:) :: S1, S2

 REAL(KIND=DP) :: rhoinf, uinf, vinf, pinf
 REAL(KIND=DP) :: dt, ctime


 INTEGER, PARAMETER :: FREE_STRM = 0 
 INTEGER, PARAMETER :: SS_VORTEX = 1
 INTEGER, PARAMETER :: X_SINWAVE = 2
 INTEGER, PARAMETER :: EU_VORTEX = 3
 INTEGER, PARAMETER :: T_ASCII = 0, T_BINARY = 1
 INTEGER, ALLOCATABLE, DIMENSION (:,:) :: iface2fp, jface2fp
 INTEGER :: N
 INTEGER :: INIT_COND
 INTEGER :: ITER, ITERMAX
 INTEGER :: RK_stage
 INTEGER :: TECFREQ, OUT_FORMAT, NRE

 INTEGER :: flag = 0
 
 
 END MODULE setup
 !----------------------------------------------------------------------------!


 MODULE MESH2D

 USE setup, ONLY: dp

 REAL(KIND=DP), ALLOCATABLE, DIMENSION (:) :: XV, YV
 REAL(KIND=DP), ALLOCATABLE, DIMENSION (:) :: XVMP, YVMP
 REAL(KIND=DP), ALLOCATABLE, DIMENSION (:) :: XVMP_VEL, YVMP_VEL

 
 INTEGER, ALLOCATABLE, DIMENSION (:,:) :: IVCELL, IVBOUN, IF2V
 INTEGER, ALLOCATABLE, DIMENSION (:,:) :: IC2F, IF2C
 INTEGER, ALLOCATABLE, DIMENSION (:)   :: BOUN_TAG, IPHYSGRP
 INTEGER, ALLOCATABLE, DIMENSION (:)   :: IBF2F
 INTEGER, ALLOCATABLE, DIMENSION (:)   :: IBFINLE, IBFOUTL, IBFSYMM, IBFPERO
 INTEGER, ALLOCATABLE, DIMENSION (:)   :: IBFINTER
 INTEGER, PARAMETER :: MAXCELL = 1000, MAXBOUNTYPE = 10, MAXBOUN = 1000
 INTEGER, PARAMETER :: MAXFACES = 10000

 INTEGER :: IVFACE(4,2)
 INTEGER :: NVERT, NCELL, NFACES
 INTEGER :: NBOUNTYPE, NBOUN, NINLE, NOUTL, NSYMM, NPERO, NINTER, NUKWN


 CHARACTER (LEN = 50) :: PROJECT_NAME
 CHARACTER (LEN = 16) :: FACEMARKER_BOUN(MAXBOUN)
 CHARACTER (LEN = :), ALLOCATABLE, DIMENSION (:) :: FACEMARKER

 END MODULE MESH2D
 !----------------------------------------------------------------------------!


